---
.travis.yml:
  docker_sets:
    - set: centos-7
      collection: puppet5
    - set: centos-7
      collection: puppet6
    - set: centos-6
      collection: puppet5
    - set: centos-6
      collection: puppet6
  user: treydock
  secure: "eQ2DMNNi1f7J8B+kzJcb1Udi3fMf21gchyprlO/VTdezdetMiJq/rVIQdTWw4KOLIHE/bG6l/S9SMo1becEppzHPKF89HKyOArAD5G6gIPJxP7Jb6l0+dys8zLWHW1szmrcyt1xpBwcf1w3Ahq2uhwETT8oNpKzPJGgTz5LsQXs="
.gitlab-ci.yml:
  delete: true
appveyor.yml:
  delete: true
spec/acceptance/nodesets/debian-8.yml:
  delete: true
spec/acceptance/nodesets/debian-9.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1404.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1604.yml:
  delete: true
spec/acceptance/nodesets/ubuntu-1804.yml:
  delete: true
